In [1]:
import numpy as np

# Array Creation

### Q.no1)Create a 1-dimensional array of integers from 1 to 10.

In [2]:
arr_int = np.arange(1,11)
arr_int

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Q.no2) Create a 2-dimensional array with random float values of shape (3, 4).

In [3]:
arr_2D = np.random.rand(3,4)
arr_2D

array([[0.78210954, 0.94984511, 0.79143954, 0.3938349 ],
       [0.38813548, 0.84278924, 0.31522275, 0.03986756],
       [0.49415981, 0.26040345, 0.239295  , 0.88122064]])

### Q.no3) Create a 3-dimensional array of zeros with shape (2, 3, 4).

In [4]:
arr_3D = np.zeros((2,3,4))
arr_3D

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Array Operations

### Q.no4) Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.

In [5]:
arr_one = np.array([1,2,3,4])
arr_two = np.array([4,3,2,1])
addition = np.add(arr_one , arr_two)
subtraction = np.subtract(arr_one , arr_two)
multiplication = np.multiply(arr_one , arr_two)
division = np.divide(arr_one , arr_two)
print('addition' , addition)
print('subtraction' , subtraction)
print('multiplication' , multiplication)
print('division' , division)

addition [5 5 5 5]
subtraction [-3 -1  1  3]
multiplication [4 6 6 4]
division [0.25       0.66666667 1.5        4.        ]


### Q.no5) Calculate the mean, median, and standard deviation of a given 1-dimensional array.

In [6]:
arr_num = np.array([2,3,4,5,6])
mean = np.mean(arr_num)
median = np.median(arr_num)
st_deviation = np.std(arr_num)
print('Mean',mean)
print('Median',median)
print('standard deviation',st_deviation)

Mean 4.0
Median 4.0
standard deviation 1.4142135623730951


### Q.no6) Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).

In [7]:
arr_1D = np.array([2,3,4,5,6,7])
arr_2D = arr_1D.reshape(2,3)
print('Shape of 1 dimesional array',arr_1D.shape)
print('After reshaping',arr_2D.shape)



Shape of 1 dimesional array (6,)
After reshaping (2, 3)


 # Array Indexing and Slicing

### Q.no7) Extract the first row and last column of a 2-dimensional array.

In [8]:
arr_2D = np.array([[1,2,3,4],[5,6,7,8]])
first_row = arr_2D[0,:]
print('First Row',first_row)
last_col = arr_2D[:,-1]
print('Last Column',last_col)


First Row [1 2 3 4]
Last Column [4 8]


### Q.no8)Reverse the order of elements in a 1-dimensional array.

In [9]:
arr_1D = np.arange(2,15,3)
print('Order of Element',arr_1D)
rev_1D = arr_1D[::-1]
print('After reversing',rev_1D)

Order of Element [ 2  5  8 11 14]
After reversing [14 11  8  5  2]


### Q.no9) Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).

In [10]:
arr_2D = np.array([[20,3,41],[60,7,8]])
cnd_stmt = (arr_2D % 2 == 0) & (arr_2D > 8)
result = arr_2D[cnd_stmt]
result

array([20, 60])

# Array Broadcasting

### Q.no10) Add a scalar value to each element of a 2-dimensional array.

In [11]:
arr_2D = np.array([[2,3,4,5],[6,7,8,9]])
scaler = 1
result = arr_2D + scaler
result

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

### Q.no 11) Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.

In [12]:
arr_1D = np.array([1,2,3])
arr_2D = np.array([[2,3,4],[5,6,7]])
result = arr_1D * arr_2D
print('One dimesional array',arr_1D)
print('Two dimesional array',arr_2D)
print('Result',result)


One dimesional array [1 2 3]
Two dimesional array [[2 3 4]
 [5 6 7]]
Result [[ 2  6 12]
 [ 5 12 21]]


#            Linear Algebra:

### Q.no12) Calculate the dot product of two 1-dimensional arrays.

In [13]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,10])
result = np.dot(arr_1,arr_2)
result


130

### Q.no13) Compute the matrix multiplication of two 2-dimensional arrays.

In [14]:
arr_1 = np.array([[1,2,3,4],[5,6,7,8]])
arr_2 = np.array([[9,10],[4,5],[1,2],[3,4]])
result = arr_1 @ arr_2
result

array([[ 32,  42],
       [100, 126]])

### Q.no14) Find the inverse and determinant of a square matrix.

In [15]:
square_matrix=  np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
determinant = np.linalg.det(square_matrix)
print('Determinant',determinant)
inverse_matrix = np.linalg.inv(square_matrix)
print('Original matrix',square_matrix)
print('Inverse matrix',inverse_matrix)

Determinant 0.9999999999999987
Original matrix [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse matrix [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
